### ISSUE TITLE
Pioneer v1.3 - Can only bring up one core

### ISSUE THREAD

**Issue by kth5** [milkv-community/linux#1]
Compiled a kernel using the `v6.8-sg2042-milkv-community` branch at ref `dfe9dcc4b86297e415d9ffd67fbf1194df9e1ff8`. 

It boots fine - albeit very slow - but then it turns out only one core of the 64 total are active. The rest is detected but marked `offline` as indicated by `lscpu`:

![image](https://github.com/milkv-community/linux/assets/1784992/65df806e-a86a-49c0-bdf1-539fcd5f4b11)

According to `dmesg` it "fails to bring online" the rest of them:

![image](https://github.com/milkv-community/linux/assets/1784992/5d3e66d9-879a-45f6-be8a-ba0e35836a10)

Attemting to bring any of the offline cores online manually results in `Unknown error 254` or straight invalid argument when stripping the trailing newline. The kernel just mentions that the CPU failed to start yet again:

![image](https://github.com/milkv-community/linux/assets/1784992/969506b3-746e-495d-9115-496253172cb5)

This is on Arch POWER (gcc (GCC) 13.2.1 20230801, GNU ld (GNU Binutils) 2.42.0). `.config` derived from `sophgo_mango_normal_defconfig`. Due to its length, available upon request.

**Comment by silvanshade** [comment]
> `.config` derived from `sophgo_mango_normal_defconfig`. Due to its length, available upon request.

If you post it I could give it a try on my side and see what happens.

Did you change anything related to CPU hotplug functionality?

**Comment by kth5** [comment]
I've rolled back to just the `normal_defconfig` and added just what I needed, build is running now.

Previous config that boots in the above mentioned way:
https://archlinuxpower.org/share/issues/sophgo/20240325_6.8.0-milkv-community-single-core-only/config

Regarding the bootloader, I'm still unable to produce a build of `sophgo/bootloader-riscv` so I'm rolling with the original Milk-V Fedora based stuff unfortunately.

**Comment by kth5** [comment]
Seems I got it to work with this config:
https://archlinuxpower.org/share/issues/sophgo/20240325_6.8.0-milkv-community-single-core-only/config.minimal

Previous was enabling most options that I've had for the 6.1.22 based kernel on https://github.com/milkv-pioneer/linux-riscv. Seems as if there indeed were options I should not have enabled.

Now seeing all 64 cores and running some stability tests:
![image](https://github.com/milkv-community/linux/assets/1784992/bbd1258c-5295-446d-a0f8-59b2eab07df1)

**Comment by silvanshade** [comment]
> Seems I got it to work with this config:

That's good to hear.

I'm not sure exactly why only the 1 hart is active on boot and whether this is intended behavior with `6.8`. (I seem to recall that this is how it is supposed to work in the early bootflow stages at least).

I think we should be able to automatically re-enable the extra harts through either kernel parameters or some additional configuration though and will try to add a patch for that.

**Comment by kth5** [comment]
I've noticed that the `linuxboot` kernel I use only brings up a single core when I drop into the shell instead of picking a boot option. That seems to be intentional so I did not pay too much attention to that. What I am thinking of today already is to get rid of this entirely and replace it with `petitboot` which would make it a tad more standard compliant (OpenPOWER). ;)

**Comment by silvanshade** [comment]
> I've noticed that the `linuxboot` kernel I use only brings up a single core when I drop into the shell instead of picking a boot option. That seems to be intentional so I did not pay too much attention to that.

Yes, turns out (at least in the sophgo sources), this was due to the `maxcpus=1` kernel boot parameter being specified in the device tree: see [here](https://github.com/sophgo/linux-riscv/blob/257e38596db40eef4a23412d91d57e888f20d581/arch/riscv/boot/dts/sophgo/mango-milkv-pioneer.dts#L162).

This is now fixed in commit https://github.com/milkv-community/linux/commit/2b5cf66a7b62dcbe442f6cc738aeb7402e71fd71.

> What I am thinking of today already is to get rid of this entirely and replace it with petitboot which would make it a tad more standard compliant (OpenPOWER). ;)

I think as long as the parameter is chosen in the device tree though it will still likely be a problem there too. But it would be interesting to see how that works anyway.

**Comment by kth5** [comment]
@silvanshade  Thank you for your kind attention in this case! I would close this issue from my side as things work just fine now.

**Comment by skeuchel** [comment]
For reference, as discussed on matrix the commit https://github.com/torvalds/linux/commit/6b9f29b81b155af023da95f560f738f29722b306 which landed in 6.8 may also be related. It was reverted in the vendor's master branch since then https://github.com/sophgo/linux-riscv/commit/e2697baecc1569e2c25d679f15c52068b124ac3e. I will also try to play with the `maxcpu` setting, because I would prefer that over reverting what seems to be a bugfix in the upstream kernel.
